name: Metrics
on:
  schedule: [{cron: "00 12 * * 1,2,3,4,5,6"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: .github/src/metrics.base.svg
          base: header, activity, community, repositories, discussions, metadata
          plugin_lines: yes
          plugin_traffic: yes
          plugin_discussions: yes
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@master
        with:
          filename: .github/src/metrics.plugin.isocalendar.svg
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@master
        with:
          filename: .github/src/metrics.plugin.habits.charts.svg
          base: ""
          plugin_habits: yes
          plugin_habits_from: 300       # Use 200 events to compute habits
          plugin_habits_days: 14        # Keep only events from last 14 days
          plugin_habits_facts: no       # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: no        # Trim unused hours on daily chart
          config_timezone: Europe/Paris # Set timezone
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          # template: repository
          filename: .github/src/metrics.plugin.followup.user.svg
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@master
        with:
          base: ""
          filename: .github/src/metrics.plugin.languages.details.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          plugin_languages_sections: recently-used
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@master
        with:
          base: ""
          filename: .github/src/metrics.plugin.languages.details2.svg
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.reactions.svg
          base: ""
          plugin_reactions: yes
          # plugin_reactions_display: relative
          plugin_reactions_details: percentage
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.people.repository.svg
          base: ""
          plugin_people: yes
          plugin_people_types: followers, contributors, stargazers, watchers
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with: 
          filename: .github/src/metrics.plugin.starlists.languages.svg
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 3
          plugin_starlists: yes
          plugin_starlists_languages: yes
          plugin_starlists_shuffle_repositories: yes
          plugin_starlists_limit_languages: disable
          plugin_starlists_limit: 3
          plugin_starlists_limit_repositories: 3
          token: NOT_NEEDED
      - uses: lowlighter/metrics@latest
        with: 
          filename: .github/src/metrics.plugin.achievements.compact.svg
          base: ""
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          # plugin_achievements_only: >-
          #  polyglot, stargazer, sponsor, deployer, member, maintainer, developer,
          #  scripter, packager, explorer, infographile, manager
          plugin_achievements_display: detailed
          token: ${{ secrets.METRICS_TOKEN }}
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.skyline.svg
          base: ""
          plugin_skyline: yes
          plugin_skyline_year: 2022         # current-year
          plugin_skyline_frames: 110        # 120=full-loop, 60=half-loop
          plugin_skyline_quality: 0.75      # default=0.5, max=1
          plugin_skyline_compatibility: yes # This uses CSS animations rather than embedded GIF to support a wider range of browser (FF/Saf). Increase file size.
          token: NOT_NEEDED
      - uses: lowlighter/metrics@latest
        with:
          filename: .github/src/metrics.plugin.calendar.full.svg
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 0
          token: ${{ secrets.METRICS_TOKEN }}


