name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.METRICS_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_OS: "False"
          SHOW_COMMIT: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_SHORT_INFO: "False"